### ISSUE TITLE
Collectivism / Individualism axe is flipped

### ISSUE THREAD

**Issue by emnificent** [10compasses/10compasses.github.io#10]
As mentioned in issue #6, I can confirm the `Collectivism / Individualism` axe is flipped, here's the results I get:

![download](https://user-images.githubusercontent.com/49172724/139838415-3920c3b0-b6f4-4c0c-8c72-21f1167bfcb7.png)
<img width="540" alt="w20SPVszmB" src="https://user-images.githubusercontent.com/49172724/139838454-32b55923-275a-4ade-836f-5fefaba4033c.png">
As you can see, I'm clearly more collective than individual, yet the `Collectivism / Individualism` axe show that I'm more individual, and crosschecking with my political beliefs, this is clearly wrong.

This is an easy fix: simply invert the two labels in the three HTML files.

**Comment by emnificent** [comment]
And regarding the first issue mentioned in #6: the `Revolution / Peaceful` axe being possibly flipped, I can't confirm nor deny it, I'm roughly in the middle, but since the `Collectivism / Individualism` axe is flipped it's possible it's the case for this one as well. I'd tend to believe their investigation and crosschecking against their political beliefs, but I invite you to check it yourself. 
In the case it'd be flipped, this would be "harder" to fix as the issue is also reported on the first generated image.

**Comment by emnificent** [comment]
Also, please consider the suggestions in #7, they will be useful, as in my case it's hard to understand if I'm `Rehabilitive` or `Punitive`

**Comment by Aashishkebab** [comment]
@10Groups  The axes were originally correct, the weights on the questions were wrong. This commit 7c17dc6 is erroneous.

I've reversed it again in #14 but also corrected the question values/calculations that caused the issue in the first place as well as a lot of other calculation errors.

**Comment by Aashishkebab** [comment]
> @10Groups The axes were originally correct, the weights on the questions were wrong. This commit [7c17dc6](https://github.com/10Groups/10groups.github.io/commit/7c17dc659c14d0022a9eb21e153547525b8212f6) is erroneous.
> 
> I've reversed it again in #14 but also corrected the question values/calculations that caused the issue in the first place as well as a lot of other calculation errors.

Actually no no wait, they are saying the wrong this entirely. It should be Moderate vs Radical, NOT Collectivism vs Individualism.
It's based on those axes from the graphs in the code. Updated #14 to match this.

And actually the Moderate vs Radical already in there aren't referenced or updated AT ALL.
