### ISSUE TITLE
Authoritarian "Communism"

### ISSUE THREAD

**Issue by ProletarianBanner** [10compasses/10compasses.github.io#12]
Change the Authoritarian "Communism" to Authoritarian Socialism because Communism involves a stateless, classless, moneyless society with the means of production held in common, a lack of wage labour, and a lack of commodity production and Socialism is merely the temporary transitory stage towards the achievement of such a society. The nations which you most likely considered to be "Communist" were only Marxist-Leninist State-Socialist nations. Those Marxist-Leninist nations weren't even authoritarian anyway and featured Socialist Democracy, People's Democracy, Proletarian Democracy, and Democratic Centralism all of which are Leninist and Marxist-Leninist principles and forms of democracy.

**Comment by 10Groups** [comment]
I will change it later, because images are harder to change. Please remind me if I don't do so in the next few days.
